version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: locatech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: clubs
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    image: locatech
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always

